In [16]:
import polars as pl

In [17]:
df = pl.read_parquet("bloomberg.parquet")

In [18]:
df

shape: (521, 60)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ('TY1     ┆ ('TY1     ┆ ('TY1     ┆ ('TY1     ┆ … ┆ ('USSO2   ┆ ('USSO3   ┆ ('USSO4   ┆ Date     │
│ Comdty',  ┆ Comdty',  ┆ Comdty',  ┆ Comdty',  ┆   ┆ CMPN      ┆ CMPN      ┆ CMPN      ┆ ---      │
│ 'fut_impl ┆ 'px_volum ┆ 'current_ ┆ 'px_last' ┆   ┆ Curncy',  ┆ Curncy',  ┆ Curncy',  ┆ date     │
│ ied_re…   ┆ e')       ┆ contra…   ┆ )         ┆   ┆ 'px_last… ┆ 'px_last… ┆ 'px_last… ┆          │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│ f64       ┆ f64       ┆ str       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ -0.45551  ┆ 611675.0  ┆ MAR 10    ┆ 115.53125 ┆ … ┆ 1.141     ┆ 1.781     ┆ 2.2965    ┆ 2010-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 04       │
│ -0.4254   ┆ 750738.0  ┆ MAR 10    ┆ 116.20312 ┆ … ┆ 1.0935    ┆ 1.715     ┆ 2.218     ┆ 2010-01- │
│           ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 05       │
│ -0.41411  ┆ 854860.0  ┆ MAR 10    ┆ 115.96875 ┆ … ┆ 1.081     ┆ 1.739     ┆ 2.2505    ┆ 2010-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 06       │
│ -0.40285  ┆ 689962.0  ┆ MAR 10    ┆ 115.84375 ┆ … ┆ 1.1005    ┆ 1.753     ┆ 2.2845    ┆ 2010-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 07       │
│ -0.50397  ┆ 998501.0  ┆ MAR 10    ┆ 116.03125 ┆ … ┆ 1.0545    ┆ 1.7275    ┆ 2.263     ┆ 2010-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 08       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.442     ┆ 0.994     ┆ 1.443     ┆ 2011-07- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 04       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.115     ┆ 0.2445    ┆ 0.482     ┆ 2011-09- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 05       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.154     ┆ 0.29      ┆ 0.498     ┆ 2011-11- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 24       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.2       ┆ 0.314     ┆ 0.517     ┆ 2011-12- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 26       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.634     ┆ 1.172     ┆ 1.638     ┆ 2011-04- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 22       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
df.null_count()

shape: (1, 60)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬──────┐
│ ('TY1      ┆ ('TY1      ┆ ('TY1      ┆ ('TY1      ┆ … ┆ ('USSO2   ┆ ('USSO3   ┆ ('USSO4   ┆ Date │
│ Comdty',   ┆ Comdty',   ┆ Comdty',   ┆ Comdty',   ┆   ┆ CMPN      ┆ CMPN      ┆ CMPN      ┆ ---  │
│ 'fut_impli ┆ 'px_volume ┆ 'current_c ┆ 'px_last') ┆   ┆ Curncy',  ┆ Curncy',  ┆ Curncy',  ┆ u32  │
│ ed_re…     ┆ ')         ┆ ontra…     ┆ ---        ┆   ┆ 'px_last… ┆ 'px_last… ┆ 'px_last… ┆      │
│ ---        ┆ ---        ┆ ---        ┆ u32        ┆   ┆ ---       ┆ ---       ┆ ---       ┆      │
│ u32        ┆ u32        ┆ u32        ┆            ┆   ┆ u32       ┆ u32       ┆ u32       ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪══════╡
│ 20         ┆ 15         ┆ 17         ┆ 16         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0    │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴──────┘

In [12]:
df.__len__()

521