In [32]:
import polars as pl

In [33]:
df = pl.read_parquet("../data_manual/bloomberg.parquet")

In [34]:
df

shape: (23, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ('TY2     ┆ ('TY2     ┆ ('TY2     ┆ ('TY2     ┆ … ┆ ('91282CL ┆ ('91282CM ┆ ('91282CM ┆ Date     │
│ Comdty',  ┆ Comdty',  ┆ Comdty',  ┆ Comdty',  ┆   ┆ K Govt',  ┆ C Govt',  ┆ K Govt',  ┆ ---      │
│ 'fut_impl ┆ 'px_volum ┆ 'current_ ┆ 'px_last' ┆   ┆ 'px_last' ┆ 'px_last' ┆ 'px_last' ┆ date     │
│ ied_re…   ┆ e')       ┆ contra…   ┆ )         ┆   ┆ )         ┆ )         ┆ )         ┆          │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│ f64       ┆ f64       ┆ str       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4.38634   ┆ 166.0     ┆ JUN 25    ┆ 108.78125 ┆ … ┆ 96.917969 ┆ 100.17968 ┆ null      ┆ 2025-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ 02       │
│ 4.38609   ┆ 112.0     ┆ JUN 25    ┆ 108.60937 ┆ … ┆ 96.738281 ┆ 99.945312 ┆ null      ┆ 2025-01- │
│           ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 03       │
│ 4.40792   ┆ 373.0     ┆ JUN 25    ┆ 108.5     ┆ … ┆ 96.675781 ┆ 99.820312 ┆ null      ┆ 2025-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 06       │
│ 4.38279   ┆ 1760.0    ┆ JUN 25    ┆ 108.14062 ┆ … ┆ 96.542969 ┆ 99.539062 ┆ null      ┆ 2025-01- │
│           ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 07       │
│ 4.32778   ┆ 569.0     ┆ JUN 25    ┆ 108.07812 ┆ … ┆ 96.566406 ┆ 99.539062 ┆ null      ┆ 2025-01- │
│           ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 08       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 4.25272   ┆ 6491.0    ┆ JUN 25    ┆ 108.90625 ┆ … ┆ 97.113281 ┆ 100.42187 ┆ 99.664062 ┆ 2025-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ 29       │
│ 4.29012   ┆ 5198.0    ┆ JUN 25    ┆ 109.20312 ┆ … ┆ 97.167969 ┆ 100.49218 ┆ 99.742188 ┆ 2025-01- │
│           ┆           ┆           ┆ 5         ┆   ┆           ┆ 8         ┆           ┆ 30       │
│ 4.30885   ┆ 4769.0    ┆ JUN 25    ┆ 108.8125  ┆ … ┆ 97.136719 ┆ 100.35937 ┆ 99.601562 ┆ 2025-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ 31       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 96.863281 ┆ 100.10937 ┆ null      ┆ 2025-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ 01       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 96.671875 ┆ 99.804688 ┆ null      ┆ 2025-01- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 20       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [35]:
# Select columns whose names contain 'TY2', and keep Date as well
ty2_cols = [col for col in df.columns if 'TY2' in str(col)]
if "Date" not in ty2_cols:
    ty2_cols.append("Date")
df_ty2 = df.select(ty2_cols)
df_ty2

shape: (23, 7)
┌──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┐
│ ('TY2        ┆ ('TY2        ┆ ('TY2       ┆ ('TY2       ┆ ('TY2       ┆ ('TY2       ┆ Date       │
│ Comdty', 'fu ┆ Comdty',     ┆ Comdty',    ┆ Comdty',    ┆ Comdty',    ┆ Comdty',    ┆ ---        │
│ t_implied_re ┆ 'px_volume') ┆ 'current_co ┆ 'px_last')  ┆ 'fut_ctd_cu ┆ 'fut_cnvs_f ┆ date       │
│ …            ┆ ---          ┆ ntra…       ┆ ---         ┆ sip'…       ┆ acto…       ┆            │
│ ---          ┆ f64          ┆ ---         ┆ f64         ┆ ---         ┆ ---         ┆            │
│ f64          ┆              ┆ str         ┆             ┆ str         ┆ f64         ┆            │
╞══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╡
│ 4.38634      ┆ 166.0        ┆ JUN 25      ┆ 108.78125   ┆ 91282CMC    ┆ 0.9202      ┆ 2025-01-02 │
│ 4.38609      ┆ 112.0        ┆ JUN 25      ┆ 108.609375  ┆ 91282CMC    ┆ 0.9202      ┆ 2025-01-03 │
│ 4.40792      ┆ 373.0        ┆ JUN 25      ┆ 108.5       ┆ 91282CMC    ┆ 0.9202      ┆ 2025-01-06 │
│ 4.38279      ┆ 1760.0       ┆ JUN 25      ┆ 108.140625  ┆ 91282CMC    ┆ 0.9202      ┆ 2025-01-07 │
│ 4.32778      ┆ 569.0        ┆ JUN 25      ┆ 108.078125  ┆ 91282CMC    ┆ 0.9202      ┆ 2025-01-08 │
│ …            ┆ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …          │
│ 4.25272      ┆ 6491.0       ┆ JUN 25      ┆ 108.90625   ┆ 91282CMC    ┆ 0.9202      ┆ 2025-01-29 │
│ 4.29012      ┆ 5198.0       ┆ JUN 25      ┆ 109.203125  ┆ 91282CMK    ┆ 0.9136      ┆ 2025-01-30 │
│ 4.30885      ┆ 4769.0       ┆ JUN 25      ┆ 108.8125    ┆ 91282CMK    ┆ 0.9136      ┆ 2025-01-31 │
│ null         ┆ null         ┆ null        ┆ null        ┆ null        ┆ null        ┆ 2025-01-01 │
│ null         ┆ null         ┆ null        ┆ null        ┆ null        ┆ null        ┆ 2025-01-20 │
└──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┘

In [36]:
df_only = df.filter(pl.col("Date") == pl.date(2025, 12, 31)).select(
    [col for col in df.columns if 'fut_implied_repo_rt' in str(col)]
)
df_only

shape: (0, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ ('TY2 Comdty',    ┆ ('FV2 Comdty',    ┆ ('TU2 Comdty',    ┆ ('US2 Comdty',    ┆ ('WN2 Comdty',   │
│ 'fut_implied_re…  ┆ 'fut_implied_re…  ┆ 'fut_implied_re…  ┆ 'fut_implied_re…  ┆ 'fut_implied_re… │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ f64               ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [37]:
df.null_count()

shape: (1, 43)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬──────┐
│ ('TY2      ┆ ('TY2      ┆ ('TY2      ┆ ('TY2      ┆ … ┆ ('91282CL ┆ ('91282CM ┆ ('91282CM ┆ Date │
│ Comdty',   ┆ Comdty',   ┆ Comdty',   ┆ Comdty',   ┆   ┆ K Govt',  ┆ C Govt',  ┆ K Govt',  ┆ ---  │
│ 'fut_impli ┆ 'px_volume ┆ 'current_c ┆ 'px_last') ┆   ┆ 'px_last' ┆ 'px_last' ┆ 'px_last' ┆ u32  │
│ ed_re…     ┆ ')         ┆ ontra…     ┆ ---        ┆   ┆ )         ┆ )         ┆ )         ┆      │
│ ---        ┆ ---        ┆ ---        ┆ u32        ┆   ┆ ---       ┆ ---       ┆ ---       ┆      │
│ u32        ┆ u32        ┆ u32        ┆            ┆   ┆ u32       ┆ u32       ┆ u32       ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪══════╡
│ 2          ┆ 2          ┆ 2          ┆ 2          ┆ … ┆ 0         ┆ 0         ┆ 19        ┆ 0    │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴──────┘

In [38]:
df.columns

["('TY2 Comdty', 'fut_implied_repo_rt')",
 "('TY2 Comdty', 'px_volume')",
 "('TY2 Comdty', 'current_contract_month_yr')",
 "('TY2 Comdty', 'px_last')",
 "('TY2 Comdty', 'fut_ctd_cusip')",
 "('TY2 Comdty', 'fut_cnvs_factor')",
 "('FV2 Comdty', 'fut_implied_repo_rt')",
 "('FV2 Comdty', 'current_contract_month_yr')",
 "('FV2 Comdty', 'px_last')",
 "('FV2 Comdty', 'fut_ctd_cusip')",
 "('FV2 Comdty', 'fut_cnvs_factor')",
 "('FV2 Comdty', 'px_volume')",
 "('TU2 Comdty', 'fut_implied_repo_rt')",
 "('TU2 Comdty', 'current_contract_month_yr')",
 "('TU2 Comdty', 'px_last')",
 "('TU2 Comdty', 'fut_ctd_cusip')",
 "('TU2 Comdty', 'fut_cnvs_factor')",
 "('TU2 Comdty', 'px_volume')",
 "('US2 Comdty', 'fut_implied_repo_rt')",
 "('US2 Comdty', 'px_volume')",
 "('US2 Comdty', 'current_contract_month_yr')",
 "('US2 Comdty', 'px_last')",
 "('US2 Comdty', 'fut_ctd_cusip')",
 "('US2 Comdty', 'fut_cnvs_factor')",
 "('WN2 Comdty', 'fut_implied_repo_rt')",
 "('WN2 Comdty', 'current_contract_month_yr')",
 "('WN2 Comdty', 'px_last')",
 "('WN2 Comdty', 'fut_ctd_cusip')",
 "('WN2 Comdty', 'fut_cnvs_factor')",
 "('WN2 Comdty', 'px_volume')",
 "('USSOB CMPN Curncy', 'px_last')",
 "('USSOC CMPN Curncy', 'px_last')",
 "('USSOD CMPN Curncy', 'px_last')",
 "('USSOE CMPN Curncy', 'px_last')",
 "('USSOF CMPN Curncy', 'px_last')",
 "('USSOI CMPN Curncy', 'px_last')",
 "('912810QN Govt', 'px_last')",
 "('912810TL Govt', 'px_last')",
 "('91282CKE Govt', 'px_last')",
 "('91282CLK Govt', 'px_last')",
 "('91282CMC Govt', 'px_last')",
 "('91282CMK Govt', 'px_last')",
 'Date']

In [39]:
cols_needed = [
    "('USSOB CMPN Curncy', 'px_last')",
    "('USSOC CMPN Curncy', 'px_last')",
    "('USSOF CMPN Curncy', 'px_last')",
    "('USSOD CMPN Curncy', 'px_last')",
    "('USSOE CMPN Curncy', 'px_last')",
    "('USSOI CMPN Curncy', 'px_last')",
]

df_usso = df.select(cols_needed)
df_usso

shape: (23, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ ('USSOB CMPN   ┆ ('USSOC CMPN   ┆ ('USSOF CMPN   ┆ ('USSOD CMPN  ┆ ('USSOE CMPN  ┆ ('USSOI CMPN  │
│ Curncy',       ┆ Curncy',       ┆ Curncy',       ┆ Curncy',      ┆ Curncy',      ┆ Curncy',      │
│ 'px_last…      ┆ 'px_last…      ┆ 'px_last…      ┆ 'px_last…     ┆ 'px_last…     ┆ 'px_last…     │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 4.32786        ┆ 4.31025        ┆ 4.257          ┆ 4.2932        ┆ 4.27515       ┆ 4.20925       │
│ 4.33           ┆ 4.313          ┆ 4.26705        ┆ 4.2987        ┆ 4.2825        ┆ 4.2242        │
│ 4.33372        ┆ 4.31927        ┆ 4.27685        ┆ 4.30728       ┆ 4.2925        ┆ 4.2329        │
│ 4.33685        ┆ 4.32355        ┆ 4.28525        ┆ 4.313         ┆ 4.30025       ┆ 4.24445       │
│ 4.33505        ┆ 4.32025        ┆ 4.27975        ┆ 4.30805       ┆ 4.29625       ┆ 4.23653       │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 4.33365        ┆ 4.32965        ┆ 4.2731         ┆ 4.3143        ┆ 4.2964        ┆ 4.21425       │
│ 4.3316         ┆ 4.3281         ┆ 4.27056        ┆ 4.3129        ┆ 4.2954        ┆ 4.21575       │
│ 4.33075        ┆ 4.32755        ┆ 4.272          ┆ 4.313         ┆ 4.29155       ┆ 4.21225       │
│ 4.331          ┆ 4.315          ┆ 4.257          ┆ 4.296         ┆ 4.276         ┆ 4.207         │
│ 4.3365         ┆ 4.323          ┆ 4.278          ┆ 4.312         ┆ 4.2981        ┆ 4.2312        │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [40]:
# Select columns whose names contain either 'fut_dlv_dt_first' or 'fut_dlv_dt_last'
cols = [col for col in df.columns if 'fut_dlv_dt_first' in str(col) or 'fut_dlv_dt_last' in str(col)]
df_dates = df.select(cols)
df_dates

shape: (0, 0)
┌┐
╞╡
└┘

In [41]:
df_crsp = pl.read_parquet("../data_manual/TFZ_IRR.parquet")
df_crsp

shape: (86_455, 18)
┌───────────┬─────────────┬──────────┬────────────┬───┬────────────┬────────────┬──────────┬───────┐
│ kytreasno ┆ kycrspid    ┆ tcusip   ┆ caldt      ┆ … ┆ tdbid      ┆ tdask      ┆ tdyld    ┆ itype │
│ ---       ┆ ---         ┆ ---      ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---      ┆ ---   │
│ f64       ┆ str         ┆ str      ┆ datetime[n ┆   ┆ f64        ┆ f64        ┆ f64      ┆ f64   │
│           ┆             ┆          ┆ s]         ┆   ┆            ┆            ┆          ┆       │
╞═══════════╪═════════════╪══════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════╡
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-02 ┆ … ┆ 100.363027 ┆ 100.364257 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-03 ┆ … ┆ 100.338799 ┆ 100.339943 ┆ 0.000124 ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-06 ┆ … ┆ 100.32877  ┆ 100.332537 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-07 ┆ … ┆ 100.322727 ┆ 100.324032 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-08 ┆ … ┆ 100.315504 ┆ 100.316563 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ …         ┆ …           ┆ …        ┆ …          ┆ … ┆ …          ┆ …          ┆ …        ┆ …     │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-24 ┆ … ┆ 99.746094  ┆ 99.75      ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-26 ┆ … ┆ 99.800781  ┆ 99.804688  ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-29 ┆ … ┆ 99.839844  ┆ 99.84375   ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-30 ┆ … ┆ 99.855469  ┆ 99.859375  ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-31 ┆ … ┆ 99.804688  ┆ 99.808594  ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
└───────────┴─────────────┴──────────┴────────────┴───┴────────────┴────────────┴──────────┴───────┘

In [42]:
df_crsp_cusip = df_crsp.filter(
    (pl.col("tcusip") == "91282CMC") & (pl.col("caldt") == pl.date(2025, 1, 2))
)
df_crsp_cusip

shape: (1, 18)
┌───────────┬──────────────┬──────────┬──────────────┬───┬─────────┬────────────┬──────────┬───────┐
│ kytreasno ┆ kycrspid     ┆ tcusip   ┆ caldt        ┆ … ┆ tdbid   ┆ tdask      ┆ tdyld    ┆ itype │
│ ---       ┆ ---          ┆ ---      ┆ ---          ┆   ┆ ---     ┆ ---        ┆ ---      ┆ ---   │
│ f64       ┆ str          ┆ str      ┆ datetime[ns] ┆   ┆ f64     ┆ f64        ┆ f64      ┆ f64   │
╞═══════════╪══════════════╪══════════╪══════════════╪═══╪═════════╪════════════╪══════════╪═══════╡
│ 208335.0  ┆ 20311231.204 ┆ 91282CMC ┆ 2025-01-02   ┆ … ┆ 100.125 ┆ 100.140625 ┆ 0.000121 ┆ 2.0   │
│           ┆ 500          ┆          ┆ 00:00:00     ┆   ┆         ┆            ┆          ┆       │
└───────────┴──────────────┴──────────┴──────────────┴───┴─────────┴────────────┴──────────┴───────┘

In [43]:
df_crsp.select("tcusip").unique()

shape: (404, 1)
┌──────────┐
│ tcusip   │
│ ---      │
│ str      │
╞══════════╡
│ 91282CND │
│ 9128285M │
│ 91282CPM │
│ 91282CBP │
│ 91282CAZ │
│ …        │
│ 912810SK │
│ 9128286T │
│ 91282CDS │
│ 912828XZ │
│ 91282CAD │
└──────────┘

In [44]:
# Implied repo from calc_spread.py (first deferred contract, volume > 0)
df_irr = pl.read_parquet("../data_manual/implied_repo_first_deferred.parquet")

In [45]:
df_irr.head(20)

shape: (20, 6)
┌────────────┬────────────┬────────────┬────────────┬────────────┬─────────────────────┐
│ 2Y         ┆ 5Y         ┆ 10Y        ┆ 20Y        ┆ 30Y        ┆ Date                │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---                 │
│ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ datetime[ns]        │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═════════════════════╡
│ null       ┆ null       ┆ 448.153273 ┆ null       ┆ 459.688744 ┆ 2025-01-02 00:00:00 │
│ null       ┆ null       ┆ 449.804634 ┆ null       ┆ 465.134634 ┆ 2025-01-03 00:00:00 │
│ null       ┆ null       ┆ 447.349575 ┆ 456.675515 ┆ 468.768393 ┆ 2025-01-06 00:00:00 │
│ 423.916661 ┆ null       ┆ 450.883581 ┆ 451.004794 ┆ 467.777488 ┆ 2025-01-07 00:00:00 │
│ 421.301692 ┆ null       ┆ 438.95821  ┆ 420.609317 ┆ 447.385439 ┆ 2025-01-08 00:00:00 │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …                   │
│ 419.248697 ┆ 391.239588 ┆ 442.61756  ┆ 438.34953  ┆ 462.129023 ┆ 2025-01-24 00:00:00 │
│ 419.018468 ┆ 392.632417 ┆ 445.827285 ┆ 429.881721 ┆ 454.397597 ┆ 2025-01-27 00:00:00 │
│ 418.160531 ┆ 387.998956 ┆ 437.715665 ┆ null       ┆ 447.780962 ┆ 2025-01-28 00:00:00 │
│ 419.890394 ┆ 389.607353 ┆ 441.349233 ┆ 440.788252 ┆ 455.857194 ┆ 2025-01-29 00:00:00 │
│ 419.833467 ┆ 395.842376 ┆ 615.321293 ┆ 452.508811 ┆ 466.194915 ┆ 2025-01-30 00:00:00 │
└────────────┴────────────┴────────────┴────────────┴────────────┴─────────────────────┘

In [46]:
df_irr.tail()

shape: (5, 6)
┌────────────┬────────────┬────────────┬────────────┬────────────┬─────────────────────┐
│ 2Y         ┆ 5Y         ┆ 10Y        ┆ 20Y        ┆ 30Y        ┆ Date                │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---                 │
│ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ datetime[ns]        │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═════════════════════╡
│ 395.167599 ┆ 389.050909 ┆ 408.111067 ┆ null       ┆ 357.256943 ┆ 2025-12-24 00:00:00 │
│ 387.558747 ┆ 387.844627 ┆ 813.262466 ┆ null       ┆ 331.147395 ┆ 2025-12-26 00:00:00 │
│ 385.892389 ┆ 380.85874  ┆ 824.439403 ┆ null       ┆ 327.76942  ┆ 2025-12-29 00:00:00 │
│ 385.705479 ┆ 384.435028 ┆ 367.153797 ┆ null       ┆ 342.237581 ┆ 2025-12-30 00:00:00 │
│ 389.789808 ┆ 405.444133 ┆ 402.825803 ┆ 506.967988 ┆ 423.089102 ┆ 2025-12-31 00:00:00 │
└────────────┴────────────┴────────────┴────────────┴────────────┴─────────────────────┘

In [47]:
df_irr.null_count()

shape: (1, 6)
┌─────┬─────┬─────┬─────┬─────┬──────┐
│ 2Y  ┆ 5Y  ┆ 10Y ┆ 20Y ┆ 30Y ┆ Date │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ---  │
│ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32  │
╞═════╪═════╪═════╪═════╪═════╪══════╡
│ 4   ┆ 12  ┆ 5   ┆ 55  ┆ 0   ┆ 0    │
└─────┴─────┴─────┴─────┴─────┴──────┘

In [48]:
df_spreads = pl.read_parquet("../data_manual/arbitrage_spreads.parquet")

In [49]:
df_spreads

shape: (249, 6)
┌───────────┬───────────┬────────────┬────────────┬───────────┬─────────────────────┐
│ 2Y        ┆ 5Y        ┆ 10Y        ┆ 20Y        ┆ 30Y       ┆ Date                │
│ ---       ┆ ---       ┆ ---        ┆ ---        ┆ ---       ┆ ---                 │
│ f64       ┆ f64       ┆ f64        ┆ f64        ┆ f64       ┆ datetime[ns]        │
╞═══════════╪═══════════╪════════════╪════════════╪═══════════╪═════════════════════╡
│ null      ┆ null      ┆ 47.343273  ┆ null       ┆ 58.878744 ┆ 2025-01-02 00:00:00 │
│ null      ┆ null      ┆ 44.764634  ┆ null       ┆ 60.094634 ┆ 2025-01-03 00:00:00 │
│ null      ┆ null      ┆ 38.769575  ┆ 48.095515  ┆ 60.188393 ┆ 2025-01-06 00:00:00 │
│ 10.815661 ┆ null      ┆ 39.488581  ┆ 39.609794  ┆ 56.382488 ┆ 2025-01-07 00:00:00 │
│ 9.951692  ┆ null      ┆ 28.40321   ┆ 10.054317  ┆ 36.830439 ┆ 2025-01-08 00:00:00 │
│ …         ┆ …         ┆ …          ┆ …          ┆ …         ┆ …                   │
│ 66.073599 ┆ 54.350909 ┆ 73.411067  ┆ null       ┆ 22.556943 ┆ 2025-12-24 00:00:00 │
│ 60.455747 ┆ 55.049627 ┆ 480.467466 ┆ null       ┆ -1.647605 ┆ 2025-12-26 00:00:00 │
│ 61.372389 ┆ 50.36274  ┆ 493.943403 ┆ null       ┆ -2.72658  ┆ 2025-12-29 00:00:00 │
│ 61.060479 ┆ 53.030028 ┆ 35.748797  ┆ null       ┆ 10.832581 ┆ 2025-12-30 00:00:00 │
│ 63.140808 ┆ 70.219133 ┆ 67.600803  ┆ 171.742988 ┆ 87.864102 ┆ 2025-12-31 00:00:00 │
└───────────┴───────────┴────────────┴────────────┴───────────┴─────────────────────┘

In [50]:
df_spreads_mean = df_spreads.mean()
df_spreads_median = df_spreads.median()
print("Column means:")
print(df_spreads_mean)
print("\nColumn medians:")
print(df_spreads_median)

Column means:
shape: (1, 6)
┌───────────┬───────────┬───────────┬───────────┬──────────┬───────────────────────────────┐
│ 2Y        ┆ 5Y        ┆ 10Y       ┆ 20Y       ┆ 30Y      ┆ Date                          │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---                           │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64      ┆ datetime[ns]                  │
╞═══════════╪═══════════╪═══════════╪═══════════╪══════════╪═══════════════════════════════╡
│ 62.585479 ┆ 49.111517 ┆ 64.334413 ┆ 82.920451 ┆ 76.23362 ┆ 2025-07-01 22:21:41.204819200 │
└───────────┴───────────┴───────────┴───────────┴──────────┴───────────────────────────────┘

Column medians:
shape: (1, 6)
┌───────────┬───────────┬───────────┬──────────┬──────────┬─────────────────────┐
│ 2Y        ┆ 5Y        ┆ 10Y       ┆ 20Y      ┆ 30Y      ┆ Date                │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---      ┆ ---                 │
│ f64       ┆ f64       ┆ f64       ┆ f64      ┆ f64      ┆ datetime[ns]        │
╞═══════════╪═══════════╪═══════════╪══════════╪══════════╪═════════════════════╡
│ 68.457642 ┆ 63.629887 ┆ 66.067653 ┆ 83.18558 ┆ 74.89198 ┆ 2025-07-02 00:00:00 │
└───────────┴───────────┴───────────┴──────────┴──────────┴─────────────────────┘

In [51]:
import pandas as pd

# Try reading the file using pandas.read_stata (since the extension is .dta, likely Stata format)
df_sf_rf = pd.read_stata("../data_manual/treasury_sf_implied_rf.dta")

In [52]:
# 1.1 — spread_n = tfut_n_rf - tfut_ois_n for each tenor
for n in [2, 5, 10, 20, 30]:
    df_sf_rf[f"spread_{n}"] = df_sf_rf[f"tfut_{n}_rf"] - df_sf_rf[f"tfut_ois_{n}"]

In [53]:
df_sf_rf.tail(200)

,date,tfut_2_rf,tfut_2_ttm,tfut_ois_2,tfut_5_rf,tfut_5_ttm,tfut_ois_5,tfut_10_rf,tfut_10_ttm,tfut_ois_10,...,tfut_20_ttm,tfut_ois_20,tfut_30_rf,tfut_30_ttm,tfut_ois_30,spread_2,spread_5,spread_10,spread_20,spread_30
4767,2023-05-15,460.951996,137.0,508.082001,492.795013,137.0,508.082001,497.727997,137.0,508.082001,...,137.0,508.082001,441.964996,137.0,508.082001,-47.130005,-15.286987,-10.354004,-41.989014,-66.117004
4768,2023-05-16,463.592010,136.0,509.051788,493.705994,136.0,509.051788,498.733002,136.0,509.051788,...,136.0,509.051788,436.994995,136.0,509.051788,-45.459778,-15.345795,-10.318787,-49.124786,-72.056793
4769,2023-05-17,455.622986,135.0,511.579987,498.585999,135.0,511.579987,500.313995,135.0,511.579987,...,135.0,511.579987,427.920990,135.0,511.579987,-55.957001,-12.993988,-11.265991,-54.550995,-83.658997
4770,2023-05-18,454.040009,134.0,516.007568,497.915985,134.0,516.007568,498.179993,134.0,516.007568,...,134.0,516.007568,428.407013,134.0,516.007568,-61.967560,-18.091583,-17.827576,-53.699554,-87.600555
4771,2023-05-19,450.122986,133.0,513.648865,498.872986,133.0,513.648865,498.687012,133.0,513.648865,...,133.0,513.648865,431.404999,133.0,513.648865,-63.525879,-14.775879,-14.961853,-43.925873,-82.243866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4962,2024-02-23,472.351990,NaN,NaN,516.903015,NaN,NaN,516.239990,NaN,NaN,...,NaN,NaN,340.785004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4963,2024-02-26,474.596985,NaN,NaN,519.463989,NaN,NaN,518.020020,NaN,NaN,...,NaN,NaN,348.949005,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4964,2024-02-27,471.479004,NaN,NaN,518.603027,NaN,NaN,512.820007,NaN,NaN,...,NaN,NaN,337.423004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4965,2024-02-28,469.110992,NaN,NaN,514.466980,NaN,NaN,518.062012,NaN,NaN,...,NaN,NaN,339.269012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4966,2024-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
min_tfut_2_ttm = df_sf_rf["tfut_2_ttm"].min()
print("Min value of tfut_2_ttm:", min_tfut_2_ttm)

Min value of tfut_2_ttm: 88.0

In [55]:
df_sf_rf_mean = df_sf_rf.mean()
df_sf_rf_median = df_sf_rf.median()
print("Column means:")
print(df_sf_rf_mean)
print("\nColumn medians:")
print(df_sf_rf_median)

Column means:
date           2014-04-24 10:19:15
tfut_2_rf               128.984467
tfut_2_ttm              129.988375
tfut_ois_2              147.428162
tfut_5_rf               151.033096
tfut_5_ttm              133.935004
tfut_ois_5              158.228928
tfut_10_rf               136.42543
tfut_10_ttm             145.024504
tfut_ois_10             157.608276
tfut_20_rf              142.081207
tfut_20_ttm             145.254202
tfut_ois_20             156.306488
tfut_30_rf               96.594368
tfut_30_ttm             132.913859
tfut_ois_30             102.398773
spread_2                -27.326719
spread_5                -15.012644
spread_10               -29.487568
spread_20               -22.061771
spread_30               -15.735785
dtype: object

Column medians:
date           2014-04-23 00:00:00
tfut_2_rf                   51.702
tfut_2_ttm                   129.0
tfut_ois_2               41.232224
tfut_5_rf                74.859001
tfut_5_ttm                   134.0
tfut_ois_5               51.743057
tfut_10_rf               63.969002
tfut_10_ttm                  145.0
tfut_ois_10              48.096558
tfut_20_rf               52.288498
tfut_20_ttm                  146.0
tfut_ois_20              46.410778
tfut_30_rf               36.483501
tfut_30_ttm                  132.0
tfut_ois_30              23.087778
spread_2                -10.917334
spread_5                 -2.834999
spread_10               -14.750889
spread_20               -17.417408
spread_30                 -0.80378
dtype: object

In [56]:
# Load arbitrage implied rf (wide)
df_arb_implied_rf = pd.read_stata("../data_manual/arbitrage_implied_rf_wide.dta")
df_arb_implied_rf

,date,cip_aud_rf,cip_cad_rf,cip_chf_rf,cip_eur_rf,cip_gbp_rf,cip_jpy_rf,cip_nzd_rf,cip_sek_rf,box_6m_rf,...,tfut_10_rf,tfut_20_rf,tfut_30_rf,tswap_1_rf,tswap_2_rf,tswap_3_rf,tswap_5_rf,tswap_10_rf,tswap_20_rf,tswap_30_rf
0,2001-12-04,227.645401,NaN,188.814026,184.684860,187.289230,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,214.60,NaN,NaN,NaN,NaN,NaN,NaN
1,2001-12-05,227.005219,NaN,193.012970,186.848602,196.825348,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,235.10,NaN,NaN,NaN,NaN,NaN,NaN
2,2001-12-06,228.461090,NaN,195.464264,190.215576,192.339951,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,239.80,NaN,NaN,NaN,NaN,NaN,NaN
3,2001-12-07,230.756714,NaN,187.464371,183.196411,193.966675,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,231.30,NaN,NaN,NaN,NaN,NaN,NaN
4,2001-12-10,224.364578,NaN,182.922729,179.334213,185.234436,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,219.20,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5798,2024-02-23,541.233948,552.870850,547.398315,539.081909,542.819031,562.275330,557.172974,546.160522,NaN,...,516.239990,472.078003,340.785004,506.46,453.70,424.52,398.22,383.69,379.56,359.97
5799,2024-02-26,540.026184,553.250488,545.318359,537.841248,543.275513,557.886414,555.220581,543.445862,NaN,...,518.020020,466.795013,348.949005,508.58,456.50,427.12,400.35,385.90,381.30,362.02
5800,2024-02-27,541.000977,552.377930,553.536438,540.851135,542.917297,569.142822,554.287109,547.271851,NaN,...,512.820007,467.937012,337.423004,508.60,457.05,427.80,401.68,387.96,384.16,364.83
5801,2024-02-28,543.378418,553.159729,561.548157,543.060303,542.612000,581.052368,554.353577,549.954346,NaN,...,518.062012,451.751007,339.269012,504.94,451.77,422.95,397.10,384.46,381.35,362.45
5802,2024-02-29,541.148926,553.652466,552.253845,539.242126,541.616272,567.945068,554.106873,545.923828,NaN,...,NaN,NaN,NaN,503.26,449.95,421.46,396.40,383.50,379.36,359.95

In [57]:
# Load arbitrage spread (wide)
df_arb_spread = pd.read_stata("../data_manual/arbitrage_spread_wide.dta")
df_arb_spread

,date,box_12m,box_18m,box_6m,cal_dow,cal_ndaq,cal_spx,cds_bond_hy,cds_bond_ig,cip_aud,...,raw_tips_treas_2,raw_tips_treas_20,raw_tips_treas_5,raw_tswap_1,raw_tswap_10,raw_tswap_2,raw_tswap_20,raw_tswap_3,raw_tswap_30,raw_tswap_5
0,2001-12-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.145401,...,NaN,NaN,NaN,7.60,NaN,NaN,NaN,NaN,NaN,NaN
1,2001-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.005219,...,NaN,NaN,NaN,8.10,NaN,NaN,NaN,NaN,NaN,NaN
2,2001-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.061096,...,NaN,NaN,NaN,4.80,NaN,NaN,NaN,NaN,NaN,NaN
3,2001-12-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.456711,...,NaN,NaN,NaN,5.30,NaN,NaN,NaN,NaN,NaN,NaN
4,2001-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.464584,...,NaN,NaN,NaN,2.20,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5558,2024-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.251404,...,NaN,NaN,NaN,4.56,-41.220001,-13.77,-69.800003,-21.139999,-78.449997,-29.330000
5559,2024-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.583923,...,NaN,NaN,NaN,6.46,-42.310001,-13.30,-71.440002,-20.480000,-77.029999,-29.780001
5560,2024-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.156189,...,NaN,NaN,NaN,5.58,-42.099998,-12.50,-71.699997,-20.879999,-77.980003,-28.650000
5561,2024-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.320984,...,NaN,NaN,NaN,5.60,-43.040001,-12.95,-72.839996,-22.200001,-79.169998,-30.320000
5562,2024-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.978394,...,NaN,NaN,NaN,4.94,-42.540001,-12.23,-71.650002,-21.049999,-77.550003,-28.900000

In [58]:
# Load arbitrage strategy (wide)
df_arb_strategy = pd.read_stata("../data_manual/arbitrage_strategy_wide.dta")
df_arb_strategy

,date,cip,cal_spread,box_spread,tips_treas,tswap,tfut,cds_bond,cip_k,cal_spread_k,box_spread_k,tswap_k,tfut_k,cds_bond_k,tips_treas_k
0,2001-12-04,21.608379,NaN,NaN,NaN,7.600000,NaN,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
1,2001-12-05,19.923035,NaN,NaN,NaN,8.100000,NaN,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
2,2001-12-06,22.220226,NaN,NaN,NaN,4.800000,NaN,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
3,2001-12-07,26.546040,NaN,NaN,NaN,5.300000,NaN,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
4,2001-12-10,22.063995,NaN,NaN,NaN,2.200000,NaN,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5558,2024-02-22,14.494972,NaN,NaN,NaN,36.895714,75.650795,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
5559,2024-02-23,13.976585,NaN,NaN,NaN,37.257145,67.808380,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
5560,2024-02-26,12.163086,NaN,NaN,NaN,37.055714,66.549988,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
5561,2024-02-27,15.493202,NaN,NaN,NaN,38.017143,70.152580,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0
5562,2024-02-28,19.239838,NaN,NaN,NaN,36.980000,72.418015,NaN,8.0,3.0,3.0,7.0,5.0,2.0,4.0