In [2]:
import polars as pl

In [ ]:
df = pl.read_parquet("../data_manual/bloomberg.parquet")

In [4]:
df

shape: (261, 159)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ('TY1     ┆ ('TY1     ┆ ('TY1     ┆ ('TY1     ┆ … ┆ ('91282CN ┆ ('91282CP ┆ ('91282CP ┆ Date     │
│ Comdty',  ┆ Comdty',  ┆ Comdty',  ┆ Comdty',  ┆   ┆ W Govt',  ┆ M Govt',  ┆ Q Govt',  ┆ ---      │
│ 'fut_impl ┆ 'px_volum ┆ 'current_ ┆ 'px_last' ┆   ┆ 'px_last' ┆ 'px_last' ┆ 'px_last' ┆ date     │
│ ied_re…   ┆ e')       ┆ contra…   ┆ )         ┆   ┆ )         ┆ )         ┆ )         ┆          │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│ f64       ┆ f64       ┆ str       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4.26034   ┆ 1.518823e ┆ MAR 25    ┆ 108.8125  ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-01- │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 02       │
│ 4.20735   ┆ 1.115634e ┆ MAR 25    ┆ 108.64062 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-01- │
│           ┆ 6         ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 03       │
│ 4.2606    ┆ 1.911409e ┆ MAR 25    ┆ 108.53125 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-01- │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 06       │
│ 4.2252    ┆ 1.975306e ┆ MAR 25    ┆ 108.17187 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-01- │
│           ┆ 6         ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 07       │
│ 4.16909   ┆ 2.011218e ┆ MAR 25    ┆ 108.14062 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-01- │
│           ┆ 6         ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆ 08       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-06- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 19       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-07- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 04       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 99.671875 ┆ null      ┆ null      ┆ 2025-09- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 100.80468 ┆ 99.960938 ┆ null      ┆ 2025-11- │
│           ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆           ┆ 27       │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ 99.882812 ┆ 99.015625 ┆ 99.726562 ┆ 2025-12- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.null_count()

shape: (1, 159)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬──────┐
│ ('TY1      ┆ ('TY1      ┆ ('TY1      ┆ ('TY1      ┆ … ┆ ('91282CN ┆ ('91282CP ┆ ('91282CP ┆ Date │
│ Comdty',   ┆ Comdty',   ┆ Comdty',   ┆ Comdty',   ┆   ┆ W Govt',  ┆ M Govt',  ┆ Q Govt',  ┆ ---  │
│ 'fut_impli ┆ 'px_volume ┆ 'current_c ┆ 'px_last') ┆   ┆ 'px_last' ┆ 'px_last' ┆ 'px_last' ┆ u32  │
│ ed_re…     ┆ ')         ┆ ontra…     ┆ ---        ┆   ┆ )         ┆ )         ┆ )         ┆      │
│ ---        ┆ ---        ┆ ---        ┆ u32        ┆   ┆ ---       ┆ ---       ┆ ---       ┆      │
│ u32        ┆ u32        ┆ u32        ┆            ┆   ┆ u32       ┆ u32       ┆ u32       ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪══════╡
│ 12         ┆ 10         ┆ 10         ┆ 10         ┆ … ┆ 171       ┆ 235       ┆ 255       ┆ 0    │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴──────┘

In [6]:
df.columns

["('TY1 Comdty', 'fut_implied_repo_rt')",
 "('TY1 Comdty', 'px_volume')",
 "('TY1 Comdty', 'current_contract_month_yr')",
 "('TY1 Comdty', 'px_last')",
 "('TY1 Comdty', 'fut_ctd_cusip')",
 "('TY1 Comdty', 'fut_cnvs_factor')",
 "('FV1 Comdty', 'fut_implied_repo_rt')",
 "('FV1 Comdty', 'px_volume')",
 "('FV1 Comdty', 'current_contract_month_yr')",
 "('FV1 Comdty', 'px_last')",
 "('FV1 Comdty', 'fut_ctd_cusip')",
 "('FV1 Comdty', 'fut_cnvs_factor')",
 "('TU1 Comdty', 'fut_implied_repo_rt')",
 "('TU1 Comdty', 'px_volume')",
 "('TU1 Comdty', 'current_contract_month_yr')",
 "('TU1 Comdty', 'px_last')",
 "('TU1 Comdty', 'fut_ctd_cusip')",
 "('TU1 Comdty', 'fut_cnvs_factor')",
 "('US1 Comdty', 'fut_implied_repo_rt')",
 "('US1 Comdty', 'px_volume')",
 "('US1 Comdty', 'current_contract_month_yr')",
 "('US1 Comdty', 'px_last')",
 "('US1 Comdty', 'fut_ctd_cusip')",
 "('US1 Comdty', 'fut_cnvs_factor')",
 "('WN1 Comdty', 'fut_implied_repo_rt')",
 "('WN1 Comdty', 'px_volume')",
 "('WN1 Comdty', 'current_contract_month_yr')",
 "('WN1 Comdty', 'px_last')",
 "('WN1 Comdty', 'fut_ctd_cusip')",
 "('WN1 Comdty', 'fut_cnvs_factor')",
 "('TY2 Comdty', 'fut_implied_repo_rt')",
 "('TY2 Comdty', 'px_volume')",
 "('TY2 Comdty', 'current_contract_month_yr')",
 "('TY2 Comdty', 'px_last')",
 "('TY2 Comdty', 'fut_ctd_cusip')",
 "('TY2 Comdty', 'fut_cnvs_factor')",
 "('FV2 Comdty', 'fut_implied_repo_rt')",
 "('FV2 Comdty', 'current_contract_month_yr')",
 "('FV2 Comdty', 'px_last')",
 "('FV2 Comdty', 'fut_ctd_cusip')",
 "('FV2 Comdty', 'fut_cnvs_factor')",
 "('FV2 Comdty', 'px_volume')",
 "('TU2 Comdty', 'fut_implied_repo_rt')",
 "('TU2 Comdty', 'current_contract_month_yr')",
 "('TU2 Comdty', 'px_last')",
 "('TU2 Comdty', 'fut_ctd_cusip')",
 "('TU2 Comdty', 'fut_cnvs_factor')",
 "('TU2 Comdty', 'px_volume')",
 "('US2 Comdty', 'fut_implied_repo_rt')",
 "('US2 Comdty', 'px_volume')",
 "('US2 Comdty', 'current_contract_month_yr')",
 "('US2 Comdty', 'px_last')",
 "('US2 Comdty', 'fut_ctd_cusip')",
 "('US2 Comdty', 'fut_cnvs_factor')",
 "('WN2 Comdty', 'fut_implied_repo_rt')",
 "('WN2 Comdty', 'current_contract_month_yr')",
 "('WN2 Comdty', 'px_last')",
 "('WN2 Comdty', 'fut_ctd_cusip')",
 "('WN2 Comdty', 'fut_cnvs_factor')",
 "('WN2 Comdty', 'px_volume')",
 "('FV1 Comdty', 'fut_cont_size')",
 "('FV2 Comdty', 'fut_cont_size')",
 "('TU1 Comdty', 'fut_cont_size')",
 "('TU2 Comdty', 'fut_cont_size')",
 "('TY1 Comdty', 'fut_cont_size')",
 "('TY2 Comdty', 'fut_cont_size')",
 "('US1 Comdty', 'fut_cont_size')",
 "('US2 Comdty', 'fut_cont_size')",
 "('WN1 Comdty', 'fut_cont_size')",
 "('WN2 Comdty', 'fut_cont_size')",
 "('FV1 Comdty', 'fut_dlv_dt_first')",
 "('FV2 Comdty', 'fut_dlv_dt_first')",
 "('TU1 Comdty', 'fut_dlv_dt_first')",
 "('TU2 Comdty', 'fut_dlv_dt_first')",
 "('TY1 Comdty', 'fut_dlv_dt_first')",
 "('TY2 Comdty', 'fut_dlv_dt_first')",
 "('US1 Comdty', 'fut_dlv_dt_first')",
 "('US2 Comdty', 'fut_dlv_dt_first')",
 "('WN1 Comdty', 'fut_dlv_dt_first')",
 "('WN2 Comdty', 'fut_dlv_dt_first')",
 "('FV1 Comdty', 'fut_dlv_dt_last')",
 "('FV2 Comdty', 'fut_dlv_dt_last')",
 "('TU1 Comdty', 'fut_dlv_dt_last')",
 "('TU2 Comdty', 'fut_dlv_dt_last')",
 "('TY1 Comdty', 'fut_dlv_dt_last')",
 "('TY2 Comdty', 'fut_dlv_dt_last')",
 "('US1 Comdty', 'fut_dlv_dt_last')",
 "('US2 Comdty', 'fut_dlv_dt_last')",
 "('WN1 Comdty', 'fut_dlv_dt_last')",
 "('WN2 Comdty', 'fut_dlv_dt_last')",
 "('FV1 Comdty', 'fut_tick_size')",
 "('FV2 Comdty', 'fut_tick_size')",
 "('TU1 Comdty', 'fut_tick_size')",
 "('TU2 Comdty', 'fut_tick_size')",
 "('TY1 Comdty', 'fut_tick_size')",
 "('TY2 Comdty', 'fut_tick_size')",
 "('US1 Comdty', 'fut_tick_size')",
 "('US2 Comdty', 'fut_tick_size')",
 "('WN1 Comdty', 'fut_tick_size')",
 "('WN2 Comdty', 'fut_tick_size')",
 "('FV1 Comdty', 'fut_val_pt')",
 "('FV2 Comdty', 'fut_val_pt')",
 "('TU1 Comdty', 'fut_val_pt')",
 "('TU2 Comdty', 'fut_val_pt')",
 "('TY1 Comdty', 'fut_val_pt')",
 "('TY2 Comdty', 'fut_val_pt')",
 "('US1 Comdty', 'fut_val_pt')",
 "('US2 Comdty', 'fut_val_pt')",
 "('WN1 Comdty', 'fut_val_pt')",
 "('WN2 Comdty', 'fut_val_pt')",
 "('USSO1Z CMPN Curncy', 'px_last')",
 "('USSOA CMPN Curncy', 'px_last')",
 "('USSOB CMPN Curncy', 'px_last')",
 "('USSOC CMPN Curncy', 'px_last')",
 "('USSOF CMPN Curncy', 'px_last')",
 "('USSO1 CMPN Curncy', 'px_last')",
 "('USSO2 CMPN Curncy', 'px_last')",
 "('USSO3 CMPN Curncy', 'px_last')",
 "('USSO4 CMPN Curncy', 'px_last')",
 "('912810QH Govt', 'px_last')",
 "('912810QN Govt', 'px_last')",
 "('912810QQ Govt', 'px_last')",
 "('912810TL Govt', 'px_last')",
 "('912810TV Govt', 'px_last')",
 "('912810TW Govt', 'px_last')",
 "('912810TZ Govt', 'px_last')",
 "('912810UB Govt', 'px_last')",
 "('912810UF Govt', 'px_last')",
 "('912810UJ Govt', 'px_last')",
 "('912810UL Govt', 'px_last')",
 "('91282CEP Govt', 'px_last')",
 "('91282CFF Govt', 'px_last')",
 "('91282CFM Govt', 'px_last')",
 "('91282CFV Govt', 'px_last')",
 "('91282CGM Govt', 'px_last')",
 "('91282CGQ Govt', 'px_last')",
 "('91282CJP Govt', 'px_last')",
 "('91282CKE Govt', 'px_last')",
 "('91282CKT Govt', 'px_last')",
 "('91282CKV Govt', 'px_last')",
 "('91282CLK Govt', 'px_last')",
 "('91282CLU Govt', 'px_last')",
 "('91282CLZ Govt', 'px_last')",
 "('91282CMA Govt', 'px_last')",
 "('91282CMB Govt', 'px_last')",
 "('91282CMC Govt', 'px_last')",
 "('91282CME Govt', 'px_last')",
 "('91282CMK Govt', 'px_last')",
 "('91282CMR Govt', 'px_last')",
 "('91282CMT Govt', 'px_last')",
 "('91282CNA Govt', 'px_last')",
 "('91282CNF Govt', 'px_last')",
 "('91282CNG Govt', 'px_last')",
 "('91282CNJ Govt', 'px_last')",
 "('91282CNR Govt', 'px_last')",
 "('91282CNW Govt', 'px_last')",
 "('91282CPM Govt', 'px_last')",
 "('91282CPQ Govt', 'px_last')",
 'Date']

In [7]:
df_crsp = pl.read_parquet("TFZ_IRR.parquet")
df_crsp

shape: (86_455, 18)
┌───────────┬─────────────┬──────────┬────────────┬───┬────────────┬────────────┬──────────┬───────┐
│ kytreasno ┆ kycrspid    ┆ tcusip   ┆ caldt      ┆ … ┆ tdbid      ┆ tdask      ┆ tdyld    ┆ itype │
│ ---       ┆ ---         ┆ ---      ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---      ┆ ---   │
│ f64       ┆ str         ┆ str      ┆ datetime[n ┆   ┆ f64        ┆ f64        ┆ f64      ┆ f64   │
│           ┆             ┆          ┆ s]         ┆   ┆            ┆            ┆          ┆       │
╞═══════════╪═════════════╪══════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════╡
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-02 ┆ … ┆ 100.363027 ┆ 100.364257 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-03 ┆ … ┆ 100.338799 ┆ 100.339943 ┆ 0.000124 ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-06 ┆ … ┆ 100.32877  ┆ 100.332537 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-07 ┆ … ┆ 100.322727 ┆ 100.324032 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 204084.0  ┆ 20250215.10 ┆ 912810ET ┆ 2025-01-08 ┆ … ┆ 100.315504 ┆ 100.316563 ┆ 0.00012  ┆ 1.0   │
│           ┆ 7620        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ …         ┆ …           ┆ …        ┆ …          ┆ … ┆ …          ┆ …          ┆ …        ┆ …     │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-24 ┆ … ┆ 99.746094  ┆ 99.75      ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-26 ┆ … ┆ 99.800781  ┆ 99.804688  ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-29 ┆ … ┆ 99.839844  ┆ 99.84375   ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-30 ┆ … ┆ 99.855469  ┆ 99.859375  ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
│ 208501.0  ┆ 20271231.20 ┆ 91282CPS ┆ 2025-12-31 ┆ … ┆ 99.804688  ┆ 99.808594  ┆ 0.000094 ┆ 2.0   │
│           ┆ 3380        ┆          ┆ 00:00:00   ┆   ┆            ┆            ┆          ┆       │
└───────────┴─────────────┴──────────┴────────────┴───┴────────────┴────────────┴──────────┴───────┘

In [11]:
# Implied repo from calc_spread.py (first deferred contract, volume > 0)
df_irr = pl.read_parquet("../data_manual/implied_repo_first_deferred.parquet")

In [10]:
df_irr

shape: (249, 6)
┌───────────┬───────────┬───────────┬───────────┬───────────┬─────────────────────┐
│ 2Y        ┆ 5Y        ┆ 10Y       ┆ 20Y       ┆ 30Y       ┆ Date                │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---                 │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ datetime[ns]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══════════╪═════════════════════╡
│ null      ┆ null      ┆ 21.769503 ┆ null      ┆ 21.845159 ┆ 2025-01-02 00:00:00 │
│ null      ┆ null      ┆ 21.849544 ┆ null      ┆ 22.068038 ┆ 2025-01-03 00:00:00 │
│ null      ┆ null      ┆ 21.788623 ┆ 22.307642 ┆ 22.248016 ┆ 2025-01-06 00:00:00 │
│ 20.587738 ┆ null      ┆ 21.949086 ┆ 22.161245 ┆ 22.255661 ┆ 2025-01-07 00:00:00 │
│ 20.501715 ┆ null      ┆ 21.503232 ┆ 21.026433 ┆ 21.498932 ┆ 2025-01-08 00:00:00 │
│ …         ┆ …         ┆ …         ┆ …         ┆ …         ┆ …                   │
│ 14.226034 ┆ 30.615047 ┆ 29.034759 ┆ null      ┆ 31.955553 ┆ 2025-12-24 00:00:00 │
│ 13.89557  ┆ 30.75449  ┆ 44.689748 ┆ null      ┆ 30.933301 ┆ 2025-12-26 00:00:00 │
│ 13.823369 ┆ 30.744024 ┆ 45.345728 ┆ null      ┆ 31.092208 ┆ 2025-12-29 00:00:00 │
│ 13.815398 ┆ 31.017345 ┆ 13.105101 ┆ null      ┆ 32.009052 ┆ 2025-12-30 00:00:00 │
│ 13.994017 ┆ 31.995779 ┆ 14.501729 ┆ 39.573402 ┆ 35.757454 ┆ 2025-12-31 00:00:00 │
└───────────┴───────────┴───────────┴───────────┴───────────┴─────────────────────┘